---
- name: apt_repository | install - Add ondrej/php repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  become: true
  tags: web, install
  when: ansible_host in groups['apache_php']


- name: apt | install - Install PHP 7.4 and libs
  apt:
    pkg:
    - php7.4
    - php7.4-curl
    - php7.4-gd
    - php7.4-mbstring
    - php7.4-mcrypt
    - php7.4-mysql
    - php7.4-soap
    - php7.4-xml
    - php7.4-zip
    - php7.4-xdebug
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-calendar
    - php7.4-dom
    - php7.4-ftp
    - php7.4-json
    - php7.4-mysqli
    - php7.4-opcache
    - php7.4-pdo
    - php7.4-simplexml
    - php7.4-xsl
    state: present
  become: true
  tags: web, install
  when: ansible_host in groups['apache_php']


- name: apt | install - Install apache2 and libs
  apt:
    pkg:
      - apache2
      - libapache2-mod-security2
      - javascript-common
    state: present
  become: true
  tags: web, install
  when: ansible_host in groups['apache_php']

- name: apache2_module | install - Apache modules enabling
  apache2_module:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - rewrite
    - proxy
    - ssl
    - headers
    - security2
  tags: web, install
  when: ansible_host in groups['apache_php']